/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmMain.java
 *
 * Created on 22-may-2011, 13:06:41
 */
package app;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author juan
 */
public class MainForm extends javax.swing.JFrame {

    MainForm _mainform;
    /** Creates new form frmMain */
    public MainForm() {
	initComponents();
	setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/eliminar.png")).getImage());	
        _mainform = this;
        
        rb_esp.addActionListener(setEsp);
        rb_eng.addActionListener(setEng);        
        getContentPane().setBackground(Color.WHITE);
        setLanguage("eng");
        initWaitDialog();
    }

    //
    
    ActionListener setEsp = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
         setLanguage("esp"); 
      }
    };
    ActionListener setEng = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        setLanguage("eng");
      }
    };
    
    
    private void setLanguage(String lang){
        if("eng".equals(lang)){
            lb_titulo.setText("DIRECTORY & FILES REMOVER");
            btn_buscar.setToolTipText("Select Directory / File");
            btn_buscar.setText("1. Select Directory / File");
            btn_eliminar.setToolTipText("Remove Directory / File Selected");
            btn_eliminar.setText("2. Remove Directory / File");
            lb_label.setText("Selected Directory / File:");
            lb_donate.setToolTipText("Help me to continue developing free projects");
            setTitle("Directory / Files Remover v2015.09.19");
            banner.setIcon(new ImageIcon(getClass().getResource("/banners/banner-en.jpg")));
        }else{
            lb_titulo.setText("ELIMINADOR CARPETAS / ARCHIVOS");
            btn_buscar.setToolTipText("Seleccionar Carpeta / Archivo");            
            btn_buscar.setText("1. Seleccionar Carpeta / Archivo");            
            
            
            btn_eliminar.setToolTipText("Eliminar Carpeta / Archivo Seleccionado");
            btn_eliminar.setText("2. Eliminar Carpeta / Archivo");
            lb_label.setText("Carpeta / Archivo Seleccionado:");
            lb_donate.setToolTipText("Ayudame a continuar desarrollando proyectos gratuitos");
            setTitle("Eliminador Carpetas / Archivos v2015.09.19");
            banner.setIcon(new ImageIcon(getClass().getResource("/banners/banner-es.jpg")));
            
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_esp = new javax.swing.JRadioButton();
        rb_eng = new javax.swing.JRadioButton();
        btn_eliminar = new javax.swing.JButton();
        lb_titulo = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        lb_label = new javax.swing.JLabel();
        tf_directorio = new javax.swing.JTextField();
        lb_donate = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eliminador Carpetas / Archivos v2015.09.19");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onExit(evt);
            }
        });

        buttonGroup1.add(rb_esp);
        rb_esp.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        rb_esp.setText("Español");

        buttonGroup1.add(rb_eng);
        rb_eng.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        rb_eng.setSelected(true);
        rb_eng.setText("English");

        btn_eliminar.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar-2.png"))); // NOI18N
        btn_eliminar.setText("2. Eliminar");
        btn_eliminar.setToolTipText("Eliminar Carpeta/Archivo Seleccionado");
        btn_eliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 14, 4, 14));
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseOver(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseLeave(evt);
            }
        });
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        lb_titulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(0, 102, 204));
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_titulo.setText("ELIMINADOR CARPETAS / ARCHIVOS");

        btn_buscar.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carpeta-2.png"))); // NOI18N
        btn_buscar.setText("1. Seleccionar");
        btn_buscar.setToolTipText("Seleccionar Carpeta / Archivo");
        btn_buscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 14, 4, 14));
        btn_buscar.setBorderPainted(false);
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_buscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseOver(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseLeave(evt);
            }
        });
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lb_label.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lb_label.setText("Carpeta / Archivo Seleccionado:");
        lb_label.setToolTipText("");

        tf_directorio.setEditable(false);
        tf_directorio.setToolTipText("Carpeta / Archivo seleccionado");

        lb_donate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/donate.gif"))); // NOI18N
        lb_donate.setToolTipText("Apoya mi trabajo / Support my work");
        lb_donate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lb_donate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navURL(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseOver(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseLeave(evt);
            }
        });

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banners/banner-es.jpg"))); // NOI18N
        banner.setToolTipText("Apoya mi trabajo / Support my work");
        banner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        banner.setPreferredSize(new java.awt.Dimension(728, 90));
        banner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navURL(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseOver(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseLeave(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lb_titulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rb_eng)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rb_esp))
                        .addComponent(tf_directorio)
                        .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_donate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_titulo)
                    .addComponent(rb_esp)
                    .addComponent(rb_eng))
                .addGap(25, 25, 25)
                .addComponent(lb_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_directorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 60, Short.MAX_VALUE)
                        .addComponent(lb_donate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        lb_donate.getAccessibleContext().setAccessibleName("Apoya mi trabajo / Support my work");
        lb_donate.getAccessibleContext().setAccessibleDescription("https://ko-fi.com/jpgsoluciones");
        banner.getAccessibleContext().setAccessibleName("https://jpgsoluciones.com");
        banner.getAccessibleContext().setAccessibleDescription("https://jpgsoluciones.com");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    File master_file = null;
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

	JFrame ventana = new JFrame();
	ventana.setResizable(true);
	JFileChooser abrir = new JFileChooser();
	abrir.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES );
        abrir.setDialogTitle("Seleccione un directorio o archivo");
        if(rb_eng.isSelected())
            abrir.setDialogTitle("Select a Directory or File");
	abrir.setMultiSelectionEnabled(false);
	FileSystemView vista = FileSystemView.getFileSystemView();
	abrir.setFileSystemView(vista);
	int status = abrir.showDialog(ventana,"Seleccionar Carpeta");
	if (status == JFileChooser.APPROVE_OPTION) {
	    String directorio = abrir.getSelectedFile().getPath();
	    tf_directorio.setText(directorio);
	    master_file = new File(directorio);            
            tf_directorio.setToolTipText(directorio);
	}
    }//GEN-LAST:event_btn_buscarActionPerformed

    
    SwingWorker<Void, Void> sw;
    JDialog dlgProgress;

    private void initWaitDialog(){
        dlgProgress = new JDialog(this,"Espere", true);
        JLabel lblStatus = new JLabel("Procesando datos..."); // this is just a label in which you can indicate the state of the processing
        JProgressBar pbProgress = new JProgressBar(0, 100);
        /*
        JButton cancel = new JButton("Cancelar");
        cancel.addActionListener((ActionEvent e) -> {
            sw.cancel(true);
            dlgProgress.dispose();
        });
        /* */
        pbProgress.setIndeterminate(true); //we'll use an indeterminate progress bar
        dlgProgress.add(BorderLayout.NORTH, lblStatus);
        dlgProgress.add(BorderLayout.CENTER, pbProgress );
        //dlgProgress.add(BorderLayout.SOUTH,cancel);
        dlgProgress.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // prevent the user from closing the dialog
        dlgProgress.setSize(300, 90);
        dlgProgress.setLocationRelativeTo(this);

    }   
    Boolean listo = false;
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
	// TODO add your handling code here:
        sw = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                listo = FileHandler.delete(master_file);
                return null;
            }
            @Override
            protected void done() {
                String txt2 = "El proceso de eliminación se completó sin errores";
                String txt3 ="Error al elminar el elemento seleccionado \n\n Causas comunes: \n - Está siendo usado por otro proceso (usar allkill - ver blog) \n - Ya no se encuentra en la misma ubicación señalada";
                if(rb_eng.isSelected()){
                    txt2 = "The process completed sucessfully";
                    txt3 = "Error removing the selected file/dir\n\n Common error causes: \n - It's been used by other process (use allkill - see in my blog) \n - The file/dir is not currently in the submited location";
                }
                dlgProgress.dispose();//close the modal dialog
                if(listo){
                    tf_directorio.setText(null);
                    master_file = null;
                    tf_directorio.setToolTipText(null);
                    JOptionPane.showMessageDialog(_mainform,txt2,"Éxito",JOptionPane.INFORMATION_MESSAGE);   
                }else{
                    JOptionPane.showMessageDialog(_mainform,txt3,"Error",JOptionPane.ERROR_MESSAGE);	
                }
               
            }
        };

        String txt1 = "¿Seguro que desea borrar el elemento seleccionado ?, La acción no podra ser reversada";
        String txt4 = "No ha seleccionado una carpeta o archivo";
	if(rb_eng.isSelected()){
            txt1 = "Are you sure you want to delete the selected file/directory ?, this action can't be reversed";
            txt4 = "You have to select a directory or file";
        }
	if(master_file != null){
	    if( JOptionPane.showConfirmDialog(_mainform,txt1, "Atención",JOptionPane.YES_NO_OPTION,2) == JOptionPane.YES_OPTION){
                listo = false;
                sw.execute(); // this will start the processing on a separate thread
                dlgProgress.setVisible(true); //this will block user input as long as the processing task is working
            }
        }else JOptionPane.showMessageDialog(_mainform,txt4,"Atención",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btn_eliminarActionPerformed
    private void mouseOver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseOver
        // TODO add your handling code here:       
        Object obj =  evt.getSource();        
        Class c = obj.getClass();
        if("class javax.swing.JLabel".equals(c.toString())){
           JLabel lb =  (JLabel) evt.getSource() ; 
           lb.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }else{
            JButton b = (JButton) evt.getSource() ; 
            b.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }        
    }//GEN-LAST:event_mouseOver
    private void mouseLeave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseLeave
        // TODO add your handling code here:
        Object obj =  evt.getSource();        
        Class c = obj.getClass();
        if("class javax.swing.JLabel".equals(c.toString())){
           JLabel lb =  (JLabel) evt.getSource() ; 
           lb.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }else{
            JButton b = (JButton) evt.getSource() ; 
            b.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } 
    }//GEN-LAST:event_mouseLeave
    private void navURL(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navURL
        // TODO add your handling code here:
        if (Desktop.isDesktopSupported()) {
          try {
            JLabel lb =  (JLabel) evt.getSource() ;
            String url = lb.getAccessibleContext().getAccessibleDescription();
            Desktop.getDesktop().browse(new URI(url));
          } catch (IOException | URISyntaxException e) { /* TODO: error handling */ }
        }        
    }//GEN-LAST:event_navURL

    private void onExit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onExit
        setVisible(false);
        JDialog bye = new Bye(this, true);
        bye.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_onExit
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		new MainForm().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_donate;
    private javax.swing.JLabel lb_label;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JRadioButton rb_eng;
    private javax.swing.JRadioButton rb_esp;
    private javax.swing.JTextField tf_directorio;
    // End of variables declaration//GEN-END:variables
}
